version: "3.3"
services:
  app:
    build: 
      context: ./app
      dockerfile: app.dockerfile
      args:
        - userName=centrin
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    deploy:
      restart_policy:
          condition: on-failure
          delay: 2s
          max_attempts: 3
          window: 120s  
      
  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    deploy:
      restart_policy:
          condition: on-failure
          delay: 2s
          max_attempts: 3
          window: 120s

  backup:
    build: 
      context: ./scripts
      dockerfile: backup.dockerfile
      args:
        - userName=centrin
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=root
      - PG_DB=postgres
      - PG_PORT=5432
      - INIT=false
    depends_on:
      - postgres
    volumes:
      - ./backups:/app/backups
    deploy:
      restart_policy:
          condition: on-failure
          delay: 2s
          max_attempts: 3
          window: 120s
  
  init:
    build: 
      context: ./scripts
      dockerfile: restore.dockerfile
      args:
        - userName=centrin
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=root
      - PG_DB=postgres
      - PG_PORT=5432
      - INIT=true
    depends_on:
      - postgres
    volumes:
      - ./backups:/app/backups
    deploy:
      restart_policy:
          condition: on-failure
          delay: 2s
          max_attempts: 3
          window: 120s

  restore: 
    build: 
      context: ./scripts
      dockerfile: restore.dockerfile
      args:
        - userName=centrin
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=root
      - PG_DB=postgres
      - PG_PORT=5432
      - INIT=false
    depends_on:
      - postgres
    volumes:
      - ./backups:/app/backups
    deploy:
      restart_policy:
          condition: on-failure
          delay: 2s
          max_attempts: 3
          window: 120s