version: "3.3"
services:
  app:
    build: 
      context: ./app
      dockerfile: app.dockerfile
      args:
        - userName=centrin
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      
  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backup:
    build: 
      context: ./scripts
      dockerfile: backup.dockerfile
      args:
        - userName=centrin
    depends_on:
      - postgres
    volumes:
      - ./backups:/app/backups