import { Poppins } from 'next/font/google'
import './global.css';
import { ToastContainer } from 'react-toastify';

const poppins = Poppins({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="cs" className={poppins.className}>
      <body>{children}</body>
      <ToastContainer />
    </html>
  );
}
